# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      timezone: 'Europe/Berlin'
      interval: 'weekly'
    assignees:
      - 'DJBlackEagle'
    commit-message:
      prefix: 'chore(github)'
    open-pull-requests-limit: 5
    labels:
      - 'dependabot'
      - 'github-actions'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      timezone: 'Europe/Berlin'
      interval: 'weekly'
    assignees:
      - 'DJBlackEagle'
    commit-message:
      prefix: 'chore(deps)'
    open-pull-requests-limit: 20
    labels:
      - 'dependabot'
      - 'dependencies'
    versioning-strategy: increase
