name: '🎫 Todo'
description: 'A ToDo list, with a checklist. Its for the developer this issue, to make a checklist what todo on other issue.'
title: '[TODO]: '
assignees:
  - 'DJBlackEagle'
labels: ['todo']
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ We use GitHub Issues to track bug reports, feature requests and regressions

        This issue type is only for a developer of this repository.

        ---

  - type: checkboxes
    attributes:
      label: 'Is there an existing issue that is already proposing this?'
      description: 'Please search [here](./?q=is%3Aissue) to see if an issue already exists for the feature you are requesting'
      options:
        - label: 'I use the right issue type'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Describe your todo.'
      description: 'A clear and concise description of your todo and use checkbox for the task list of this todo'
      placeholder: |
        This we need todo:
          - [ ] Add something
          - [ ] Add this thing
