name: Pull-Request Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  code_format_check:
    name: Checking code format style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies 🔧
        run: yarn install --immutable
      - name: Run Prettier 📃
        run: yarn run prettier

  code_check:
    name: Linting the source code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies 🔧
        run: yarn install --immutable
      - name: Run ESLint 📝
        run: yarn run lint
